### ISSUE TITLE
Hard to know when an asset is not copied

### ISSUE THREAD

**Issue by joshbmarshall** [tangshuang/gulp-css-copy-assets#3]
Need to have a notification when an asset isn't copied, either from a typo or file missing. Is fixed in pull request #2

**Comment by tangshuang** [comment]
Thanks @joshbmarshall !
I have merged and later will build to npm package.
Later try npm install gulp-css-copy-assets.

**Comment by tangshuang** [comment]
Merged and update the package version.
Now can update by using `npm install --save-dev gulp-css-copy-assets@latest`
