### ISSUE TITLE
 what am I doing wrong?

### ISSUE THREAD

**Issue by DavoBR** [tangshuang/gulp-css-copy-assets#4]
Hi, why it say that gulpCssCopyAssets is not a function?

![2018-02-18](https://user-images.githubusercontent.com/498724/36358601-4c6d5e66-14e7-11e8-93d6-c7f813282c32.png)

Thanks

**Comment by tangshuang** [comment]
@DavoBR use like:

```
var gulpCssCopyAssets = require("gulp-css-copy-assets").default;
```

This is because I use ES6 module export, it is easy to use with ES6:

```
import gulpCssCopyAssets from "gulp-css-copy-assets";
```
